### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by juiceo** [potty/react-anchorme#12]
Hey, nice component! We would like to use it in one of our projects, but it looks like you haven't explicitly defined a license for this project so it would go against our open source dependency guidelines. Could you add one? :)

**Comment by juiceo** [comment]
Hi, any update on this? :) 

Just so you are aware of the implications of this: if your code does not have a license, it is considered copyrighted work and essentially no one can use it without violating copyright law. From [GitHub](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository): 

> You're under no obligation to choose a license. However, without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work. If you're creating an open source project, we strongly encourage you to include an open source license. The Open Source Guide provides additional guidance on choosing the correct license for your project.


I would probably recommend the MIT license for this project, that is also what anchorme.js uses. Here's a quick guide on how to add one: https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository

**Comment by juiceo** [comment]
Ah okay, my bad - you have actually defined the `license` property in `package.json` - all is good then!

Might be a good idea to still add a LICENSE.md so it's also clear in GitHub which apparently isn't picking up on the fact that it's defined in package.json

**Comment by potty** [comment]
Hi @juiceo, thank you for the suggestion. Licence file is added now, enjoy :)

**Comment by juiceo** [comment]
Thank you! 😃
