### ISSUE TITLE
Passing options to anchorme.js?

### ISSUE THREAD

**Issue by subpublic** [potty/react-anchorme#8]
Hi

Is there a way to add options, passed to anchorme.js ?

Say I'd like to do
`<Anchorme options={{truncate: 6}}>text</Anchorme>`

**Comment by potty** [comment]
Hi, I added option to truncate the text by adding `truncate` [prop](https://github.com/potty/react-anchorme/releases/tag/v2.2.0).

If you want to do some other custom transformation with the text, you can use [custom link component](https://github.com/potty/react-anchorme#custom-link-component) and transform text to match your needs.
